#!/usr/bin/env python3
"""Browser editor for drawing the global patrol route on the field grid."""

from __future__ import annotations

import argparse
import json
import math
import threading
import webbrowser
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = ROOT / "ros2_ws/src/robot_bringup/config/motion_tuning.yaml"
DEFAULT_OUTPUT = ROOT / "data/waypoint_routes/shape4_waypoint_route_v1.yaml"
FIELD_BOUNDS = (-2.0, 2.0, -2.0, 2.0)
SNAP_M = 0.25


def _node_params(data: dict[str, Any], node_name: str) -> dict[str, Any]:
    node = data.get(node_name, {})
    params = node.get("ros__parameters", {}) if isinstance(node, dict) else {}
    return params if isinstance(params, dict) else {}


def _pairs(values: Any) -> list[list[float]]:
    if not isinstance(values, list):
        return []
    numbers = [float(value) for value in values]
    return [[numbers[i], numbers[i + 1]] for i in range(0, len(numbers) - 1, 2)]


def load_editor_config(path: Path) -> dict[str, Any]:
    """Load the current route and object-grid geometry from the tuning YAML."""
    with path.open(encoding="utf-8") as stream:
        data = yaml.safe_load(stream) or {}
    mission = _node_params(data, "mission_fsm_node")
    viz = _node_params(data, "recognition_viz_node")
    rows = int(viz.get("grid_rows", 6))
    cols = int(viz.get("grid_cols", 7))
    spacing = float(viz.get("grid_spacing_m", 0.5))
    origin_x = float(viz.get("grid_origin_x_m", -1.5))
    origin_y = float(viz.get("grid_origin_y_m", -1.0))
    object_points = [
        [origin_x + col * spacing, origin_y + row * spacing]
        for row in range(rows)
        for col in range(cols)
    ]
    start = mission.get("global_zigzag_start_xy", [-1.8, 1.8])
    if not isinstance(start, list) or len(start) < 2:
        start = [-1.8, 1.8]
    return {
        "field_bounds": list(FIELD_BOUNDS),
        "snap_m": SNAP_M,
        "object_points": object_points,
        "object_grid": {
            "rows": rows,
            "cols": cols,
            "spacing_m": spacing,
            "y_min": origin_y,
            "y_max": origin_y + max(0, rows - 1) * spacing,
        },
        "start": [float(start[0]), float(start[1])],
        "current_route": _pairs(mission.get("global_zigzag_waypoints_xy", [])),
        "source_config": str(path),
    }


def validate_waypoints(payload: Any) -> list[list[float]]:
    """Validate, clamp and quarter-grid-snap route points received from the browser."""
    if not isinstance(payload, list) or len(payload) > 200:
        raise ValueError("waypoints must be a list with at most 200 points")
    xmin, xmax, ymin, ymax = FIELD_BOUNDS
    result: list[list[float]] = []
    for point in payload:
        if not isinstance(point, list) or len(point) != 2:
            raise ValueError("every waypoint must be [x, y]")
        x, y = float(point[0]), float(point[1])
        if not math.isfinite(x) or not math.isfinite(y):
            raise ValueError("waypoint coordinates must be finite")
        x = min(xmax, max(xmin, round(x / SNAP_M) * SNAP_M))
        y = min(ymax, max(ymin, round(y / SNAP_M) * SNAP_M))
        snapped = [round(x, 2), round(y, 2)]
        if not result or snapped != result[-1]:
            result.append(snapped)
    return result


def save_route(path: Path, start: list[float], waypoints: list[list[float]]) -> None:
    """Write a small ROS parameter overlay that can be copied into motion tuning."""
    flat = [coordinate for point in waypoints for coordinate in point]
    overlay = {
        "mission_fsm_node": {
            "ros__parameters": {
                "global_zigzag_start_xy": start,
                "global_zigzag_waypoints_xy": flat,
            }
        },
        "recognition_viz_node": {
            "ros__parameters": {
                "global_zigzag_start_xy": list(start),
                "global_zigzag_waypoints_xy": list(flat),
            }
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as stream:
        stream.write("# Generated by shape4_waypoint_route_editor_v1.py\n")
        yaml.safe_dump(overlay, stream, sort_keys=False, allow_unicode=True)


HTML = r"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Shape4 Waypoint Route Editor</title>
<style>
body{margin:0;background:#111820;color:#eaf1f8;font-family:system-ui,sans-serif}
.wrap{display:flex;gap:18px;padding:18px;align-items:flex-start}.panel{width:310px}
canvas{background:#17232d;border:1px solid #52616d;max-width:calc(100vw - 370px);height:auto}
button{margin:4px 2px;padding:9px 11px;background:#263a49;color:#fff;border:1px solid #607789;border-radius:5px;cursor:pointer}
button:hover{background:#355064}.danger{background:#582b31}.save{background:#245d43}
pre{white-space:pre-wrap;background:#0d1318;padding:10px;border-radius:5px;max-height:290px;overflow:auto}
.hint{color:#afbeca;font-size:13px;line-height:1.5}.status{min-height:2.5em;color:#73e3ac}
label{display:block;margin:9px 0}.legend span{display:inline-block;width:12px;height:12px;margin-right:6px;border-radius:50%}
</style></head><body><div class="wrap">
<canvas id="field" width="820" height="820"></canvas>
<div class="panel"><h2>Waypoint 경로 편집</h2>
<div class="legend"><p><span style="background:#ffd34d"></span>물체 배치점 (0.5 m)</p><p><span style="background:#45b7ff"></span>로봇 시작점</p><p><span style="background:#ff8f3d"></span>새 경로</p></div>
<p id="gridInfo" class="hint"></p>
<p class="hint">좌클릭: 0.25 m 격자에 waypoint 추가<br>우클릭 또는 U: 마지막 점 취소<br>숫자는 방문 순서입니다.</p>
<button id="undo">되돌리기</button><button id="clear" class="danger">전체 지우기</button>
<button id="load">현재 경로 불러오기</button>
<label><input id="reference" type="checkbox" checked> 현재 경로를 회색으로 표시</label>
<label><input id="rotate" type="checkbox" checked> 메인 UI처럼 180° 회전</label>
<button id="save" class="save">YAML 저장</button><button id="copy">값 복사</button>
<p class="status" id="status"></p><h3>global_zigzag_waypoints_xy</h3><pre id="output">[]</pre>
</div></div>
<script>
const canvas=document.getElementById('field'),ctx=canvas.getContext('2d'),pad=58;
let cfg=null, points=[]; const W=canvas.width,H=canvas.height;
const rotate=()=>document.getElementById('rotate').checked;
function sx(x){let t=(x-cfg.field_bounds[0])/(cfg.field_bounds[1]-cfg.field_bounds[0]);if(rotate())t=1-t;return pad+t*(W-2*pad)}
function sy(y){let t=(cfg.field_bounds[3]-y)/(cfg.field_bounds[3]-cfg.field_bounds[2]);if(rotate())t=1-t;return pad+t*(H-2*pad)}
function world(px,py){let tx=(px-pad)/(W-2*pad),ty=(py-pad)/(H-2*pad);if(rotate()){tx=1-tx;ty=1-ty}let x=cfg.field_bounds[0]+tx*(cfg.field_bounds[1]-cfg.field_bounds[0]);let y=cfg.field_bounds[3]-ty*(cfg.field_bounds[3]-cfg.field_bounds[2]);return [Math.round(x/cfg.snap_m)*cfg.snap_m,Math.round(y/cfg.snap_m)*cfg.snap_m]}
function line(a,b,color,width=3,arrow=true){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(sx(a[0]),sy(a[1]));ctx.lineTo(sx(b[0]),sy(b[1]));ctx.stroke();if(!arrow)return;let ang=Math.atan2(sy(b[1])-sy(a[1]),sx(b[0])-sx(a[0])),q=11;ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(sx(b[0]),sy(b[1]));ctx.lineTo(sx(b[0])-q*Math.cos(ang-.45),sy(b[1])-q*Math.sin(ang-.45));ctx.lineTo(sx(b[0])-q*Math.cos(ang+.45),sy(b[1])-q*Math.sin(ang+.45));ctx.fill()}
function route(route,color,width,labels){let prev=cfg.start;route.forEach((p,i)=>{line(prev,p,color,width,true);ctx.fillStyle=color;ctx.beginPath();ctx.arc(sx(p[0]),sy(p[1]),7,0,7);ctx.fill();if(labels){ctx.font='bold 14px sans-serif';ctx.fillText(String(i+1),sx(p[0])+9,sy(p[1])-8)}prev=p})}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#17232d';ctx.fillRect(0,0,W,H);
for(let v=-2;v<=2.001;v+=.25){let major=Math.abs((v*2)-Math.round(v*2))<1e-6;ctx.strokeStyle=major?'#49606f':'#293b47';ctx.lineWidth=major?1.4:.7;line([v,-2],[v,2],ctx.strokeStyle,ctx.lineWidth,false);line([-2,v],[2,v],ctx.strokeStyle,ctx.lineWidth,false)}
ctx.fillStyle='#b9c8d2';ctx.font='12px monospace';for(let v=-2;v<=2.001;v+=.5){ctx.fillText(v.toFixed(2),sx(v)-16,H-23);ctx.fillText(v.toFixed(2),10,sy(v)+4)}
cfg.object_points.forEach(p=>{ctx.fillStyle='#ffd34d';ctx.beginPath();ctx.arc(sx(p[0]),sy(p[1]),5,0,7);ctx.fill();ctx.strokeStyle='#352b00';ctx.stroke()});
ctx.fillStyle='#45b7ff';ctx.beginPath();ctx.arc(sx(cfg.start[0]),sy(cfg.start[1]),10,0,7);ctx.fill();ctx.fillStyle='#d9f1ff';ctx.fillText('START',sx(cfg.start[0])+12,sy(cfg.start[1])-10);
if(document.getElementById('reference').checked)route(cfg.current_route,'#68747d',2,false);route(points,'#ff8f3d',4,true);updateOutput()}
function flat(){return points.flat().map(v=>Number(v.toFixed(2)))}
function updateOutput(){document.getElementById('output').textContent='['+flat().join(', ')+']'}
canvas.addEventListener('click',e=>{let r=canvas.getBoundingClientRect(),p=world((e.clientX-r.left)*W/r.width,(e.clientY-r.top)*H/r.height);if(p[0]>=-2&&p[0]<=2&&p[1]>=-2&&p[1]<=2){if(!points.length||points.at(-1)[0]!=p[0]||points.at(-1)[1]!=p[1])points.push(p);draw()}});
canvas.addEventListener('contextmenu',e=>{e.preventDefault();points.pop();draw()});
document.getElementById('undo').onclick=()=>{points.pop();draw()};document.getElementById('clear').onclick=()=>{points=[];draw()};document.getElementById('load').onclick=()=>{points=cfg.current_route.map(p=>[...p]);draw()};
document.getElementById('rotate').onchange=draw;document.getElementById('reference').onchange=draw;
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='u'){points.pop();draw()}});
document.getElementById('copy').onclick=async()=>{await navigator.clipboard.writeText('global_zigzag_waypoints_xy: ['+flat().join(', ')+']');document.getElementById('status').textContent='클립보드에 복사했습니다.'};
document.getElementById('save').onclick=async()=>{let res=await fetch('/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({waypoints:points})});let data=await res.json();document.getElementById('status').textContent=data.ok?'저장 완료: '+data.path:'저장 실패: '+data.error};
fetch('/config',{cache:'no-store'}).then(r=>r.json()).then(data=>{cfg=data;document.getElementById('gridInfo').textContent=`물체 격자 Y: ${cfg.object_grid.y_min.toFixed(2)} ~ ${cfg.object_grid.y_max.toFixed(2)} m`;draw()});
</script></body></html>"""


def make_handler(config_path: Path, output: Path) -> type[BaseHTTPRequestHandler]:
    """Create a request handler bound to one editor configuration."""

    class Handler(BaseHTTPRequestHandler):
        def _json(self, data: dict[str, Any], status: HTTPStatus = HTTPStatus.OK) -> None:
            body = json.dumps(data, ensure_ascii=False).encode("utf-8")
            self.send_response(status)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_GET(self) -> None:  # noqa: N802
            if self.path == "/config":
                self._json(load_editor_config(config_path))
                return
            if self.path not in {"/", "/index.html"}:
                self.send_error(HTTPStatus.NOT_FOUND)
                return
            body = HTML.encode("utf-8")
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_POST(self) -> None:  # noqa: N802
            if self.path != "/save":
                self.send_error(HTTPStatus.NOT_FOUND)
                return
            try:
                length = min(int(self.headers.get("Content-Length", "0")), 65536)
                payload = json.loads(self.rfile.read(length).decode("utf-8"))
                waypoints = validate_waypoints(payload.get("waypoints"))
                current_config = load_editor_config(config_path)
                save_route(output, current_config["start"], waypoints)
                self._json({"ok": True, "path": str(output), "waypoints": waypoints})
            except (ValueError, TypeError, json.JSONDecodeError) as exc:
                self._json({"ok": False, "error": str(exc)}, HTTPStatus.BAD_REQUEST)

        def log_message(self, format_string: str, *args: Any) -> None:
            print(f"[route-editor] {format_string % args}")

    return Handler


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8767)
    parser.add_argument("--no-browser", action="store_true")
    args = parser.parse_args()

    config_path = args.config.resolve()
    # Fail early with a clear error before binding the server port.
    load_editor_config(config_path)
    output = args.output.resolve()
    server = ThreadingHTTPServer((args.host, args.port), make_handler(config_path, output))
    local_url = f"http://127.0.0.1:{args.port}/"
    print(f"Waypoint route editor: {local_url}")
    print(f"Saved route overlay: {output}")
    print("Stop with Ctrl-C.")
    if not args.no_browser:
        threading.Timer(0.4, lambda: webbrowser.open(local_url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
